analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3500819,"name"\:"SQA_Project_3-25/26","teamId"\:3497093,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3508803,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3497093,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
