<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_You have been logged out successfully</name>
   <tag></tag>
   <elementGuidId>1f9532c7-9761-43d8-a0c4-fe2faa588515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'You have been logged out successfully.' or . = 'You have been logged out successfully.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You have been logged out successfully.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7653f456-cd65-4716-9dc8-4fd038eb83f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have been logged out successfully.</value>
      <webElementGuid>22aeb114-7f35-4e4a-97b1-0b18b59bea35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1fde3fa9442d03ace9f8a7d69abc3cdd</value>
      <webElementGuid>1d358b98-70be-4b25-a137-f50f6e9df186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>80859cde-6003-4de6-8de0-a63944efb356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>305d2c44-7931-4e64-b648-dfcc07b9eb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'You have been logged out successfully.' or . = 'You have been logged out successfully.')]</value>
      <webElementGuid>d73ec2a0-a768-4830-be9f-0df8d275b61f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
